name: kisaanguide4
description: An elegant, modern agricultural management and analytics app designed for Pakistani farmers, featuring real-time weather alerts, crop advisory modules, and interactive expense tracking.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  animated_bottom_navigation_bar: ^1.4.0
  intl: ^0.20.2
  weather: ^3.2.1
  shared_preferences: ^2.5.5
  google_generative_ai: ^0.4.0
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
