// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBotQdOXRfMn3YQGC86AX8Q0ZWBjHvBNEk',
    appId: '1:318450145188:web:107c8c960e9f879f685331',
    messagingSenderId: '318450145188',
    projectId: 'kisaanguide4',
    authDomain: 'kisaanguide4.firebaseapp.com',
    storageBucket: 'kisaanguide4.firebasestorage.app',
    measurementId: 'G-ESQE0L0VER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASRCpsVrjZ34Fls9Y43RSw4MH9vCQP99E',
    appId: '1:318450145188:android:7ede9842e13140ff685331',
    messagingSenderId: '318450145188',
    projectId: 'kisaanguide4',
    storageBucket: 'kisaanguide4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ2Ldhs5B3OCt7kfVJOHZCgbNWw1aQMsg',
    appId: '1:318450145188:ios:9a14d81798d0057a685331',
    messagingSenderId: '318450145188',
    projectId: 'kisaanguide4',
    storageBucket: 'kisaanguide4.firebasestorage.app',
    iosBundleId: 'com.example.kisaanguide4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ2Ldhs5B3OCt7kfVJOHZCgbNWw1aQMsg',
    appId: '1:318450145188:ios:9a14d81798d0057a685331',
    messagingSenderId: '318450145188',
    projectId: 'kisaanguide4',
    storageBucket: 'kisaanguide4.firebasestorage.app',
    iosBundleId: 'com.example.kisaanguide4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBotQdOXRfMn3YQGC86AX8Q0ZWBjHvBNEk',
    appId: '1:318450145188:web:ab6a1631cd8cd6af685331',
    messagingSenderId: '318450145188',
    projectId: 'kisaanguide4',
    authDomain: 'kisaanguide4.firebaseapp.com',
    storageBucket: 'kisaanguide4.firebasestorage.app',
    measurementId: 'G-FDRJKFHKLF',
  );
}
